/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AxiomIngestToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CanarySigningSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ControlApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HealthAggregatorToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PublicCanary": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
  }
}

import "sst"
export {}