/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AxiomIngestToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CanaryNetwork": {
      "type": "sst.aws.Vpc"
    }
    "CanarySigningSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CanaryTelemetryCollector": {
      "service": string
      "type": "sst.aws.Service"
    }
    "ControlApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ControlPlane": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "HealthAggregator": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "HealthAggregatorToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Network": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "NotificationService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "ProxyRouter": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "PublicCanary": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "RouteState": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "StatusApplication": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "TelemetryCollector": {
      "service": string
      "type": "sst.aws.Service"
    }
  }
}

import "sst"
export {}