import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("SST isolates AWS resources behind a provider-selected deployment module", () => {
  const root = readFileSync("sst.config.ts", "utf8");
  const aws = readFileSync("infra/providers/aws.ts", "utf8");
  const awsPolicy = readFileSync("infra/providers/aws-policy.ts", "utf8");

  assert.doesNotMatch(root, /DEPLOYMENT_PROVIDER|process\.env/);
  assert.match(root, /infra\/providers\/aws\.js/);
  assert.match(root, /import\("\.\/infra\/providers\/aws\.js"\)/);
  assert.match(root, /awsDeployment\.(app|run)/);
  assert.doesNotMatch(root, /sst\.aws\.|new aws\./);

  assert.match(aws, /new sst\.Secret\("AxiomIngestToken", \$dev \? "unused-in-sst-dev" : undefined\)/);
  assert.match(aws, /new sst\.Secret\("ControlApiToken", \$dev \? devControlApiToken : undefined\)/);
  assert.match(aws, /new sst\.Secret\("HealthAggregatorToken", \$dev \? devHealthAggregatorToken : undefined\)/);
  assert.match(aws, /"CanarySigningSecret",\s*\$dev \? devCanarySigningSecret : undefined/);
  assert.match(aws, /schemaVersion: 3/);
  assert.match(aws, /new sst\.Secret\("ControlApiIdentities"\)/);
  assert.match(aws, /CONTROL_API_IDENTITIES_JSON: controlIdentitiesSecret/);
  assert.match(aws, /new sst\.aws\.Service\("ProxyRouter"/);
  assert.match(aws, /new sst\.aws\.Service\("ProxyRouter"[\s\S]*?dev: \{ url: "http:\/\/127\.0\.0\.1:8080" \}/);
  assert.match(aws, /const host = \$dev \? "127\.0\.0\.1"/);
  assert.match(aws, /const socks5Port = \$dev \? 1081 : 1080/);
  assert.match(aws, /SOCKS5_PROXY_PORT: String\(socks5Port\)/);
  assert.match(aws, /socks5h:\/\/\$\{host\}:\$\{socks5Port\}/);
  assert.match(aws, /new sst\.aws\.Service\("ControlPlane"/);
  assert.match(aws, /new sst\.aws\.Service\("HealthAggregator"/);
  assert.match(aws, /new sst\.aws\.Service\("CompanyDashboard"/);
  assert.match(aws, /companyDashboard: status\.url/);
  assert.doesNotMatch(aws, /internalDashboard/);
  assert.match(aws, /new sst\.aws\.Service\("UsageAccounting"/);
  assert.match(aws, /new sst\.aws\.Service\("NotificationService"/);
  assert.match(aws, /new sst\.aws\.Service\("TelemetryCollector"/);
  assert.match(aws, /new sst\.aws\.Service\("CanaryTelemetryCollector"/);
  assert.match(aws, /new sst\.aws\.ApiGatewayV2\("PublicCanary"/);
  assert.match(aws, /handler: "src\/canary-lambda\.handler"/);
  assert.doesNotMatch(aws, /new sst\.aws\.Service\("PublicCanary"/);
  assert.match(aws, /new sst\.aws\.Dynamo\("IntegrationTargetState"/);
  assert.match(aws, /fields: \{ id: "string" \}/);
  assert.match(aws, /ttl: "expiresAt"/);
  assert.match(aws, /new sst\.aws\.ApiGatewayV2\("IntegrationTargetApi"/);
  assert.match(aws, /handler: "src\/integration-target-lambda\.handler"/);
  assert.doesNotMatch(aws, /handler: "src\/integration-target-lambda\.handler"[\s\S]{0,200}vpc: canaryVpc/);
  assert.match(aws, /concurrency: \{ reserved: 5 \}/);
  assert.match(aws, /new sst\.aws\.Service\("IntegrationTransportTarget"/);
  assert.match(aws, /const cloudTestStage = stage\.cloudTest/);
  assert.doesNotMatch(aws, /DEPLOY_INTEGRATION_TARGET/);
  assert.match(aws, /new aws\.lb\.LoadBalancer\("ProxyLoadBalancer"/);
  assert.match(aws, /new aws\.lb\.TargetGroup\("ProxyHttpBlueTarget"/);
  assert.match(aws, /new aws\.lb\.TargetGroup\("ProxyHttpGreenTarget"/);
  assert.match(aws, /new aws\.lb\.TargetGroup\("ProxySocksBlueTarget"/);
  assert.match(aws, /new aws\.lb\.TargetGroup\("ProxySocksGreenTarget"/);
  assert.match(aws, /strategy: "BLUE_GREEN"/);
  assert.match(aws, /lifecycleStages: \["POST_PRODUCTION_TRAFFIC_SHIFT"\]/);
  assert.match(aws, /alternateTargetGroupArn: httpGreenTarget\.arn/);
  assert.match(aws, /alternateTargetGroupArn: socksGreenTarget\.arn/);
  assert.match(aws, /tcpIdleTimeoutSeconds: nlbTcpIdleTimeoutSeconds/);
  assert.match(aws, /httpListenerIdleTimeoutSeconds: tlsEnabled \? 350 : nlbTcpIdleTimeoutSeconds/);
  assert.match(aws, /socks5ListenerIdleTimeoutSeconds: nlbTcpIdleTimeoutSeconds/);
  assert.match(aws, /deregistrationDelay: nlbDeregistrationDelaySeconds/);
  assert.match(aws, /connectionTermination: false/);
  assert.match(aws, /iam::aws:policy\/AmazonECSInfrastructureRolePolicyForLoadBalancers/);
  assert.doesNotMatch(aws, /iam::aws:policy\/service-role\/AmazonECSInfrastructureRolePolicyForLoadBalancers/);
  assert.match(awsPolicy, /geoIpDatabaseSource: "\.sst\/geoip\/GeoLite2-City\.mmdb"/);
  assert.match(aws, /copyFiles: geoIpBundleConfigured/);
  assert.match(aws, /otlp_http\/axiom_logs/);
  assert.match(aws, /otlp_http\/axiom_traces/);
  assert.match(aws, /otlp_http\/axiom_metrics/);
  assert.match(aws, /x-axiom-dataset/);
  assert.match(aws, /x-axiom-metrics-dataset/);
  assert.match(aws, /sending_queue/);
  assert.match(aws, /retry_on_failure/);
  assert.match(aws, /logs\/operational/);
  assert.match(aws, /logs\/security/);
  assert.match(aws, /log\.category/);
  assert.ok(
    aws.split("x-axiom-dataset: \\${env:AXIOM_LOGS_DATASET}").length - 1 >= 3,
    "operational, security, and general log exporters must share the log dataset",
  );
  assert.doesNotMatch(aws, /AXIOM_SECURITY_LOGS_DATASET|SECURITY_LOG_RETENTION_DAYS/);
  assert.match(aws, /endpoint: 0\.0\.0\.0:4318/);
  assert.doesNotMatch(aws, /sigv4auth|x-aws-log-group|monitoring\.\$\{region\}\.amazonaws\.com/);
});
